[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  '@rari-capital/solmate/=lib/solmate/',
  'forge-std/=lib/forge-std/src/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config